// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	IDEAS_KV: KVNamespace;
	RESEARCH_KV: KVNamespace;
	ENVIRONMENT: "production" | "development";
	R2_PUBLIC_URL: "https://pub-74ee393e7d5d490aa0ea0c5590f79b06.r2.dev" | "http://localhost:8787";
	MODEL_REASONING: "@cf/openai/gpt-oss-120b";
	MODEL_STT: "@cf/openai/whisper-large-v3-turbo";
	MODEL_VOICE_GEN: "@cf/myshell-ai/melotts";
	MODEL_SPEAKER_DETECT: "@cf/pipecat-ai/smart-turn-v2";
	CHAT_COORDINATOR: DurableObjectNamespace<import("./src/index").ChatCoordinatorDO>;
	EPISODE_ACTOR: DurableObjectNamespace<import("./src/index").EpisodeActor>;
	BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
