name = 'social-investing'
main = "src/index.ts"
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]

# Logs
[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

# D1 Database for structured data
[[d1_databases]]
binding = "DB"
database_name = "sji-app-db"
database_id = "34b476f8-1f88-4062-816d-2acfb3449a7d"

# R2 Bucket for audio files and transcripts
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "sji-app-public"

# KV Namespace for session and ephemeral chat memory
[[kv_namespaces]]
binding = "KV"
id = "ae22b132a2fd453ca9cc04c1ab3b0da9"

# Legacy KV Namespaces (preserved for backward compatibility)
[[kv_namespaces]]
binding = "IDEAS_KV"
id = "b7bbdd09b9b2431286eabca8cffd2abe"


[[kv_namespaces]]
binding = "RESEARCH_KV"
id = "d93026f2fa3c40ff8048abc0ab05835e"

# Durable Objects
[[durable_objects.bindings]]
name = "CHAT_COORDINATOR"
class_name = "ChatCoordinatorDO"
# script_name = "sji-app" # Optional. Defaults to the current environment's Worker code.

[[durable_objects.bindings]]
name = "EPISODE_ACTOR"
class_name = "EpisodeActor"
# script_name = "sji-app" # Optional. Defaults to the current environment's Worker code.

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["ChatCoordinatorDO", "EpisodeActor"]

# Environment variables
[vars]
ENVIRONMENT = "production"
R2_PUBLIC_URL = "https://pub-74ee393e7d5d490aa0ea0c5590f79b06.r2.dev"
MODEL_REASONING = "@cf/openai/gpt-oss-120b"
MODEL_STT = "@cf/openai/whisper-large-v3-turbo" #Accurate, multilingual ASR
MODEL_VOICE_GEN = "@cf/myshell-ai/melotts" #Multi-speaker TTS, cheap + fast
MODEL_SPEAKER_DETECT = "@cf/pipecat-ai/smart-turn-v2" #Realtime turn segmentation

# Secrets (set via: wrangler secret put ADMIN_TOKEN)
# ADMIN_TOKEN = "your-secret-token-here"

# Assets binding for static frontend files
[assets]
directory = "./dist"
binding = "ASSETS"

# Build configuration
[build]
command = "npm run build:frontend"

# Local development settings
[env.dev]
name = "sji-app-dev"

[env.dev.vars]
ENVIRONMENT = "development"
R2_PUBLIC_URL = "http://localhost:8787"
